# This bucket holds the build logs generated by a sub-build.
# A sub-build is a build kicked off by the runner. A single runner may kick
# off many sub-builds.
resource "google_storage_bucket" "sub_build_logs" {
  project                     = var.project_id
  name                        = "sub-build-logs-${var.project_id}-${random_string.suffix.result}"
  location                    = var.region
  force_destroy               = true
  uniform_bucket_level_access = true
  lifecycle_rule {
    condition {
      age = 1
    }
    action {
      type = "Delete"
    }
  }
}

# This bucket holds test output artifacts generated by a sub-build.
resource "google_storage_bucket" "sub_build_test_output" {
  project                     = var.project_id
  name                        = "sub-build-test-output-${var.project_id}-${random_string.suffix.result}"
  location                    = var.region
  force_destroy               = true
  uniform_bucket_level_access = true
  lifecycle_rule {
    condition {
      age = 30
    }
    action {
      type = "Delete"
    }
  }
}
